# permissions for end users to view tmps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tmp
    app.kubernetes.io/managed-by: kustomize
  name: tmp-viewer-role
rules:
- apiGroups:
  - some.cn
  resources:
  - tmps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - some.cn
  resources:
  - tmps/status
  verbs:
  - get
